### ISSUE TITLE
latest der and pkcs1 inside rsa

### ISSUE THREAD

**Issue by neuronetio** [RustCrypto/RSA#120]
Hi,
I have to use `rsa` with the latest `der` and` pkcs1` packages.
Packages are ready, but `rsa` uses old versions.
When can I expect an updated version?
Thanks

![image](https://user-images.githubusercontent.com/25027696/143619479-7e945f63-a351-41bd-b491-f090adc9a795.png)

**Comment by tarcieri** [comment]
A proper upgrade will involve switching from `pkcs1` traits to the `pkcs8` traits and using the `pkcs1/pkcs8` feature.

This is because the blanket impls were reversed so the `pkcs1` traits are blanket impl'd for types which impl the `pkcs8` traits. Reversing the relationship allows for more than one blanket impl, which was used in this release to add `sec1` support to types which impl the `pkcs8` traits.

**Comment by tarcieri** [comment]
Also note that the new releases of `der`, `pkcs1`, and `pkcs8` are all 2021 edition crates, so it would be best to update them when the `rsa` crate is ready to do an edition bump as well.

**Comment by dignifiedquire** [comment]
@tarcieri can you take a stab at this when you have a moment? I tried, but I got lost in the traits between pkcs1 and pkcs8 :/

**Comment by tarcieri** [comment]
Yep. See the comment I left here: https://github.com/RustCrypto/RSA/pull/122#issuecomment-1006118136

**Comment by tarcieri** [comment]
PR to update `pkcs1` and `pkcs8` here: https://github.com/RustCrypto/RSA/pull/139
