### ISSUE TITLE
save the privatekey

### ISSUE THREAD

**Issue by readlnh** [RustCrypto/RSA#31]
Is there a feature that can save/export private key easily?

**Comment by penumbra23** [comment]
It's merged in #38 
Waiting for new crate release

**Comment by jeffrade** [comment]
@penumbra23 It looks like #38 only provides one direction (parse/from/import from a public or private key file). What I think would be nice is to be able to have functions like `to_pkcs[1|8]` and `try_to()`. 

For example, given an `RSAPublicKey`, be able to output:
```
-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK5Z7jk1ql5DquRvlPmFgyBDCvdPQ0T2
si2oPAUmNw2Z/qb2Sr/BEBoWpagFf8Gl1K4PRipJSudDl6N/Vdb2CYkCAwEAAQ==
-----END PUBLIC KEY-----
```
so that it (and an `RSAPrivateKey`) can be saved to disk.

**Comment by penumbra23** [comment]
Yup sorry, my bad. Thought that this would go in the same feature (which seems to be logical). But for any purpose you can generate the keys somewhere offline, save it and import.

**Comment by jeffrade** [comment]
> But for any purpose you can generate the keys somewhere offline, save it and import.

My use case is I generate the keys in my app using this lib like so:
```
let private_key = RSAPrivateKey::new(&mut rng, bits).expect("failed to generate a key");
let public_key: RSAPublicKey = private_key.into();
```
then I would like to persist to disk so that next time the app starts up, I can check if keys exist and use them (instead of generating a new set). Instead of using a built in Rust serializer, I would prefer to write out in [ASN.1 notation](https://tls.mbed.org/kb/cryptography/asn1-key-structures-in-der-and-pem).

**Comment by dignifiedquire** [comment]
We have full pkcs1 & pcks8 support now, so closing this.
